# Translucent violet theme
background_opacity 0.45

# Nacarado morado sutil anclado a la parte inferior de la ventana
background_image /home/jairo/.config/kitty/violet-nacarado.png
background_image_layout scaled
background_image_linear yes

# Colors
background #241a4f
foreground #e6defc
selection_background #a78bfa
selection_foreground #1c1138
cursor #c084fc
cursor_text_color #1c1138
cursor_shape block

# ANSI palette (purple-tint)
color0  #1c1138
color1  #f0719b
color2  #b6f0b0
color3  #f0d090
color4  #a78bfa
color5  #c084fc
color6  #9ce0f0
color7  #d9d0f0
color8  #4a3a8a
color9  #f49cc0
color10 #c8f5c2
color11 #f5e0a8
color12 #b9a3fb
color13 #d9a8fa
color14 #b0ebfa
color15 #ece6fc