
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080@300.00Hz",
    position = "0x0",
    scale    = "auto",
})

hl.monitor({
    output   = "DP-2",
    mode     = "1920x1080@144.00Hz",
    position = "1920x0",
    scale    = "auto",
})

---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "nautilus"
-- Lanzador de aplicaciones: nwg-drawer compacto, centrado y nacarado (SUPER)
local menu        = "nwg-drawer -is 34 -spacing 10 -c 8 -ml 220 -mr 220 -mt 130 -mb 130"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
  hl.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0")
  -- Portal de Hyprland para compartir pantalla (Discord, etc.): sin el,
  -- el selector de captura sale vacio. Ademas se reinicia el portal
  -- principal para que registre ScreenCast/Screenshot (carrera de arranque:
  -- si arranca antes que la implementacion, no los expone).
  hl.exec_cmd("systemctl --user start xdg-desktop-portal-hyprland")
  hl.exec_cmd("sleep 1 && systemctl --user restart xdg-desktop-portal")
  hl.exec_cmd("LOCPATH=/home/jairo/.locales waybar")
  -- Daemon de minimize: escucha socket2 y emula el minimize (Hyprland no
  -- oculta ventanas nativamente). El taskbar envia set_minimized y el daemon
  -- mueve al special:minimized, restaurando al hacer clic sobre el icono del
  -- taskbar. Ya no flota ventanas: todo se encuadra (mosaico) por defecto.
  hl.exec_cmd("systemd-run --user --unit=hypr-minimize-daemon "
    .. "--property=StandardOutput=journal --property=StandardError=journal "
    .. "python3 /home/jairo/.local/bin/minimize-daemon.py")
  -- Fondo de pantalla: hyprpaper (estáticos) + wallpaper engine (workshop)
  -- init_wallpaper.sh regenera la config y arranca hyprpaper si hay estado guardado;
  -- si no, arranca hyprpaper con la config por defecto.
  hl.exec_cmd("pgrep -x hyprpaper >/dev/null || hyprpaper >/dev/null 2>&1 &")
  hl.exec_cmd("sleep 2 && /home/jairo/.config/eww/scripts/init_wallpaper.sh")
  -- Genera eww.yuck con la lista de fondos incrustada (SUPER+W)
  hl.exec_cmd("python3 /home/jairo/.config/eww/scripts/list_wallpapers.py >/dev/null 2>&1")
  -- Daemon de eww para el menú de fondos (abrir con SUPER+W)
  hl.exec_cmd("pgrep -x eww >/dev/null || eww daemon >/dev/null 2>&1 &")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_THEME", "Posys_Cursor_Black")
hl.env("XCURSOR_SIZE", "18")
hl.env("HYPRCURSOR_THEME", "Posys-Cursor-Scalable-Black")
hl.env("HYPRCURSOR_SIZE", "18")
hl.env("LOCPATH", "/home/jairo/.locales")
hl.env("LANG", "es_ES.UTF-8")
hl.env("GTK_THEME", "Adwaita:dark")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("PATH", "/home/jairo/.local/bin:" .. (os.getenv("PATH") or ""))


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(c084fcee)", "rgba(7c3aedee)"}, angle = 45 },
            inactive_border = "rgba(4c3a80aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled = true,
            size    = 3,
            passes  = 2,
            noise   = 0.03,
            vibrancy = 0.30,
            vibrancy_darkness = 0.4,
            contrast = 1.20,
            brightness = 0.88,
            popups = true,
            new_optimizations = true,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })

-- Workspace con una ventana expandida (estado nativo maximized, f[1]):
-- el area de trabajo se pone a tope (sin gaps) para que la expandida ocupe
-- todo el espacio sin margenes libres. Al restaurar o al heredar el estado
-- otra ventana, la regla se reevalua sola (regla dinamica por estado).
hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering = true, -- Quita las frases que aparecen abajo del todo (ej: "To rice, or not to rice")
        -- Con una ventana expandida (maximizada) o fullscreen, al abrir o
        -- enfocar otra ventana en mosaico esta hereda el estado (queda
        -- encima) en vez de quedarse oculta debajo. Las flotantes (lanzador,
        -- barras) solo se suben al frente, sin robar el estado.
        on_focus_under_fullscreen = 1,
        -- Al cerrar la ventana que tiene el estado expandido/fullscreen, la
        -- siguiente ventana enfocada lo hereda: abres algo encima de la
        -- expandida y al cerrarlo la anterior vuelve sola a pantalla completa.
        exit_window_retains_fullscreen = 1,
    },
})

-- Calidad de imagen maxima que da el monitor (1920x1080).
-- El monitor usa escala 1.5 (fraccional); sin esto, las apps XWayland
-- (Steam, juegos) se renderizan a baja resolucion y el compositor las
-- escala, dando un aspecto pixelado.
hl.config({
    xwayland = {
        -- Renderiza las ventanas XWayland a escala nativa (nitidas) en
        -- lugar de que el compositor las estire con el factor 1.5.
        force_zero_scaling = true,
    },
})

hl.config({
    render = {
        -- Permite que las ventanas fullscreen (juegos) se presenten
        -- directamente sin pasar por el compositor: maxima nitidez.
        direct_scanout = true,
        -- Evita que texturas mas pequenas que el area se estiren borrosas.
        expand_undersized_textures = false,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "es,es",            -- espanol (dvorak) y espanol (qwerty)
        kb_variant = "dvorak,",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        repeat_rate = 22, -- DEBUG temporal

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

-- No warpear el puntero al enfocar ventanas (p.ej. al hacer clic en el
-- taskbar/dock el cursor se iba al centro de la ventana).
hl.config({
    cursor = {
        no_warps = true,
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("/home/jairo/.local/bin/zapzap-toggle.sh"))
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("/home/jairo/.local/bin/drawer-toggle.sh"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("/home/jairo/.local/bin/launcher-toggle.sh 'com.brave.Browser Brave-browser Brave' flatpak run com.brave.Browser"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("/home/jairo/.local/bin/launcher-toggle.sh discord discord"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("/home/jairo/.local/bin/launcher-toggle.sh steam steam"))
hl.bind(mainMod .. " + F9", hl.dsp.exec_cmd("/home/jairo/.local/bin/pavucontrol-toggle.sh"), { description = "Abrir/cerrar pavucontrol-qt" })
hl.bind("F9", hl.dsp.exec_cmd("/home/jairo/.local/bin/gsr-toggle.sh"), { description = "Grabar clip con gpu-screen-recorder" })
hl.bind(mainMod .. " + plus", hl.dsp.send_shortcut({ mods = "CTRL + SHIFT", key = "M", window = "class:discord" }), { description = "Silenciar Discord (global)" })
hl.bind(mainMod .. " + exclamdown", hl.dsp.send_shortcut({ mods = "CTRL + SHIFT", key = "D", window = "class:discord" }), { description = "Ensordecer Discord (global)" })

-- SUPER sola abre/cierra el lanzador (wofi).
-- Workaround para la regresion de Hyprland 0.56 (fix en PR #15904, aun no
-- en 0.56.x): el bind de release de SUPER tambien se dispara tras cualquier
-- combo (SUPER+W, SUPER+1...), asi que solo lanzamos wofi si no se pulso
-- ninguna otra tecla mientras SUPER estaba pulsado.
local superHeld  = false
local superCombo = false

-- SUPER + SHIFT alterna entre espanol (dvorak) y espanol (qwerty).
-- Solo se dispara si SHIFT fue la unica tecla pulsada junto a SUPER,
-- para no estorbar a combos como SUPER+SHIFT+1 (mover a workspace).
local shiftOnly = false

local function toggleLayout()
    hl.exec_cmd("hyprctl switchxkblayout all next")
end

local superLauncher = function()
    if not superCombo then
        hl.dispatch(hl.dsp.exec_cmd("pkill wofi || wofi --show drun"))
    end
end

-- DEBUG temporal: registrar eventos de teclado
hl.on("input.keyboard.key", function(keycode, _timeMs, state)
    hl.exec_cmd("touch /tmp/kbd-evt-" .. keycode .. "-" .. state)
    if keycode == 133 or keycode == 134 then -- SUPER_L / SUPER_R
        if state == 1 then
            superHeld  = true
            superCombo = false
            shiftOnly  = false
            hl.exec_cmd("touch /tmp/kbd-SUPER-down")
        else
            superHeld = false
            hl.exec_cmd("touch /tmp/kbd-SUPER-up-shiftOnly-" .. tostring(shiftOnly))
            if shiftOnly then
                hl.exec_cmd("touch /tmp/kbd-TOGGLE")
                toggleLayout()
            end
        end
    elseif superHeld and state == 1 then
        if not superCombo then
            superCombo = true
            shiftOnly  = (keycode == 50 or keycode == 62) -- SHIFT_L / SHIFT_R
        elseif keycode ~= 50 and keycode ~= 62 then
            shiftOnly = false
        end
    end
end)

hl.bind("SUPER + SUPER_L", superLauncher, { release = true })
hl.bind("SUPER + SUPER_R", superLauncher, { release = true })
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Pantalla completa: SUPER + F (pulsar de nuevo para salir)
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen(), { description = "Pantalla completa" })

-- SUPER + ESPACIO: expande la ventana bajo el ratón con el estado nativo
-- "maximized" (ocupa el área de trabajo sin tapar la waybar). Al pulsarlo
-- de nuevo vuelve a su sitio. Al abrir o enfocar otra ventana, esta hereda
-- el estado y queda encima (misc:on_focus_under_fullscreen = 1).
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd("/home/jairo/.local/bin/window-expand-toggle.py"), { description = "Expandir ventana bajo el ratón" })

-- Abrir opencode: SUPER + ñ (toggle, enfoca si ya está abierto)
hl.bind(mainMod .. " + ntilde", hl.dsp.exec_cmd("/home/jairo/.local/bin/opencode-toggle.sh"), { description = "Abrir/enfocar opencode" })

-- Selector de fondos predefinidos: SUPER + X
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("/home/jairo/.local/bin/toggle_wallpaper_menu.sh"), { description = "Cambiar fondo de pantalla" })

-- Con el teclado Dvorak, la tecla física X escribe "q": se ata tambien SUPER+Q
-- al mismo selector para que la tecla X fisica funcione siempre.
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("/home/jairo/.local/bin/toggle_wallpaper_menu.sh"), { description = "Cambiar fondo de pantalla" })

-- Mientras el selector de fondos está abierto, Hyprland entra en este submap
-- y el menú se controla con el teclado: flechas (o h/l) para moverse,
-- Enter para aplicar, Escape (o q) para cerrar. El script de toggle sale del
-- submap al cerrar el menú.
hl.define_submap("wallpapermenu", function()
    local nav    = "/home/jairo/.config/eww/scripts/wallpaper_menu_nav.py"
    local toggle = "/home/jairo/.local/bin/toggle_wallpaper_menu.sh"
    hl.bind("left",     hl.dsp.exec_cmd(nav .. " prev"))
    hl.bind("h",        hl.dsp.exec_cmd(nav .. " prev"))
    hl.bind("right",    hl.dsp.exec_cmd(nav .. " next"))
    hl.bind("l",        hl.dsp.exec_cmd(nav .. " next"))
    hl.bind("Return",   hl.dsp.exec_cmd(nav .. " apply"))
    hl.bind("KP_Enter", hl.dsp.exec_cmd(nav .. " apply"))
    hl.bind("Escape",   hl.dsp.exec_cmd(nav .. " close"))
    hl.bind("q",        hl.dsp.exec_cmd(nav .. " close"))
    hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(toggle))
    hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(toggle))
end)

-- Capturas de pantalla -> portapapeles (pegar con Ctrl+V)
-- SUPER + SHIFT + B: seleccionar region con el raton  <- el principal
-- Print            : pantalla completa
-- SHIFT + Print    : seleccionar region con el raton
-- SUPER + Print    : ventana activa
hl.bind("Print",                    hl.dsp.exec_cmd("/home/jairo/.local/bin/screenshot.sh screen"), { description = "Captura pantalla completa" })
hl.bind("SHIFT + Print",            hl.dsp.exec_cmd("/home/jairo/.local/bin/screenshot.sh region"), { description = "Captura de region" })
hl.bind(mainMod .. " + SHIFT + B",  hl.dsp.exec_cmd("/home/jairo/.local/bin/screenshot.sh region"), { description = "Captura de region" })
hl.bind(mainMod .. " + Print",      hl.dsp.exec_cmd("/home/jairo/.local/bin/screenshot.sh window"), { description = "Captura ventana activa" })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Las ventanas se encuadran (mosaico) automáticamente: cada aplicación al
-- abrirse ocupa la mitad del hueco disponible y, con 3, 4, 5... ventanas,
-- se van repartiendo la pantalla sola. El daemon minimize-daemon.py solo
-- gestiona minimizar/restaurar desde el taskbar.

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Ventanas expandidas (estado nativo maximized): sin borde, sin esquinas
-- redondeadas ni sombra, para que se distingan del mosaico normal y no
-- parezcan flotantes. La regla es dinamica: se aplica al maximizar y se
-- revierte sola al restaurar (tambien cuando otra ventana hereda el estado).
hl.window_rule({
    name        = "maximized-flush",
    match       = { fullscreen_state_internal = 1 },
    border_size = 0,
    rounding    = 0,
    no_shadow   = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Desplegables de la barra (volumen, brillo, monitor, spotify, sistema):
-- flotantes, con las mismas esquinas y sin borde del compositor — el
-- contorno morado lo pinta su propio CSS, uno de Hyprland lo duplicaria.
hl.window_rule({
    name     = "float-bar-popups",
    match    = { class = "^(volume_popup|brightness_popup|monitor_popup|spotify_popup|system_popup)\\.py$" },
    float    = true,
    rounding = 12,
    border_size = 0,
})

-- Kitty sin desenfoque del compositor: la terminal conserva su
-- translucidez pero no desenfoca lo que hay detrás.
hl.window_rule({
    name    = "kitty-no-blur",
    match   = { class = "^kitty$" },
    no_blur = true,
})

-- Lanzador de aplicaciones (wofi): flotante, sin bordes del compositor
-- (el contorno morado lo pinta su CSS) y con esquinas a juego con su radio.
-- El desenfoque nacarado sale solo del blur global + su fondo translúcido.
hl.window_rule({
    name        = "float-wofi",
    match       = { class = "^wofi$" },
    float       = true,
    rounding    = 14,
    border_size = 0,
})

-- Explorador de archivos (nautilus) con el mismo estilo que wofi: flotante,
-- sin bordes del compositor y esquinas a juego. La transparencia la pinta el
-- propio GTK4 vía CSS (lamina rgba), sin opacity del compositor: asi el texto
-- no se apaga.
hl.window_rule({
    name        = "float-nautilus",
    match       = { class = "^(nautilus|org\\.gnome\\.Nautilus)$" },
    float       = true,
    rounding    = 14,
    border_size = 0,
})

-- Cristal nacarado en el lanzador (nwg-drawer): desenfoca el fondo tras él
hl.layer_rule({
    name  = "drawer-blur",
    match = { namespace = "^nwg-drawer$" },
    blur  = true,
})

-- Selector de fondos (SUPER+X): ventana flotante sin bordes.
-- La posición (abajo-centro) la fija el propio picker en tiempo real
-- (logical_size), así que no se define un move estático aquí.
hl.window_rule({
    name    = "float-wallpaper-picker",
    match   = { class = "wallpaper-menu" },
    float   = true,
    no_anim = true,
    rounding = 12,
})

-- Al recibir el foco una ventana (p. ej. al hacer clic sobre ella),
-- se sube al frente para que nunca quede oculta bajo otra ventana.
-- En ventanas en mosaico esto no tiene efecto (alterzorder es no-op).
hl.bind(mainMod .. " + T", function () hl.window.alter_zorder({ mode = "top" }) end, { description = "Llevar la ventana activa al frente" })

-- Sober (Roblox): el reto "Verifying you're not a bot" se abre como una
-- ventana aparte titulada "Security", creada por el proceso sober_services
-- (el WebView de WebKit). En mosaico Hyprland la estruja junto al resto de
-- ventanas del espacio y el diálogo queda inservible, así que la sacamos
-- flotante y centrada con un tamaño de diálogo razonable.
hl.window_rule({
    name   = "float-sober-security",
    match  = { class = "org\\.vinegarhq\\.Sober", title = "^Security$" },
    float  = true,
    size   = "560 700",
    center = true,
})

-- pavucontrol-qt (F9): flotante y centrada para que no quede detrás de las
-- ventanas en mosaico.
hl.window_rule({
    name   = "float-pavucontrol",
    match  = { class = "pavucontrol-qt" },
    float  = true,
    size   = "900 700",
    center = true,
})

-- ALT + TAB: pasa a la siguiente ventana y la expande (maximizada nativa).
-- Si ya hay una expandida/fullscreen, la ventana enfocada hereda el estado
-- y queda encima. Para volver a encuadrarla: SUPER + ESPACIO sobre ella.
hl.bind("ALT + TAB",         hl.dsp.exec_cmd("/home/jairo/.local/bin/alt-tab-expand.py"),        { description = "Siguiente ventana al frente (expandida)" })
hl.bind("ALT + SHIFT + TAB", hl.dsp.exec_cmd("/home/jairo/.local/bin/alt-tab-expand.py --prev"), { description = "Ventana anterior al frente (expandida)" })
