wallpaper {
    monitor = DP-1
    path = /home/jairo/Pictures/Wallpapers/anime_purple_sky.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = /home/jairo/Pictures/Wallpapers/anime_purple_sky.jpg
    fit_mode = cover
}
